//! Integer-only LUT generation (SPEC §6.3 tables, generated WITHOUT floats).
//!
//! Each table is 65 536 × i16, indexed by `t + 32768` for t ∈ [−32768, 32767]
//! (the `LUT16` saturating-index convention). The generated bytes are the
//! canonical artifact — committed by hash, identical on every platform
//! because nothing here touches libm.
//!
//! Final Q-format rounding reuses `vm::exec::rnd` — THE rounding rule.

use vm::exec::{rnd, sat16};

pub const LUT_ENTRIES: usize = 65536;

/// e^(t/2048) in Q32, computed by an i128 Taylor series.
///
/// For x = |t|/2048 ≤ 16: terms are iterated in Q32; the largest
/// intermediate is term·x_q32 < 2^55 · 2^36 = 2^91 ≪ i128. Negative inputs
/// use e^(−x) = 2^64 / (e^x·2^32) to avoid alternating-series cancellation.
/// Truncation error accumulates < ~100 ulps of Q32 — invisible after the
/// >>18 to Q14, and irrelevant to consensus (the bytes are canonical).
fn exp_q32(t: i32) -> u64 {
    let x_q32: i128 = (t.unsigned_abs() as i128) << 21; // |t|/2048 in Q32
    let mut sum: i128 = 1i128 << 32;
    let mut term: i128 = 1i128 << 32;
    for n in 1..=64 {
        term = (term * x_q32) >> 32;
        term /= n;
        sum += term;
        if term == 0 {
            break;
        }
    }
    if t < 0 {
        ((1i128 << 64) / sum) as u64
    } else {
        // e^16·2^32 < 2^56 — fits u64.
        sum as u64
    }
}

/// EXP table: input Q4.11, output sat16(rhe(e^x · 2^14)) (SPEC §6.3).
/// x ≤ −16 → 0; x = 0 → 16384; x ≳ 0.693 saturates to 32767.
pub fn gen_exp() -> Vec<i16> {
    (0..LUT_ENTRIES)
        .map(|i| {
            let t = i as i32 - 32768;
            let v = exp_q32(t);
            if v > (i64::MAX as u64) {
                32767 // e^x·2^32 ≥ 2^63 ⇒ Q14 value is astronomically saturated
            } else {
                sat16(rnd(v as i64, 18)) // Q32 → Q14, round-half-even
            }
        })
        .collect()
}

/// Floor integer square root (Newton), deterministic.
fn isqrt(n: u128) -> u128 {
    if n == 0 {
        return 0;
    }
    // Initial guess ≥ √n: 2^⌈bits/2⌉.
    let bits = 128 - n.leading_zeros();
    let mut x = 1u128 << bits.div_ceil(2);
    loop {
        let y = (x + n / x) >> 1;
        if y >= x {
            return x;
        }
        x = y;
    }
}

/// RSQRT table: input = integer mean-square m (valid domain [0, 32767]),
/// output ≈ round(2^14/√m) in Q2.14; m ≤ 0 → 32767 sentinel (SPEC §6.3).
///
/// q = ⌊√(m·2^40)⌋ ≈ √m·2^20, then r = round(2^34/q) — round-to-nearest
/// via (2^34 + q/2)/q. (Half-even vs half-up differs only on exact halves,
/// which is a quality non-event; the artifact bytes are canonical.)
pub fn gen_rsqrt() -> Vec<i16> {
    (0..LUT_ENTRIES)
        .map(|i| {
            let t = i as i32 - 32768; // table input is the sat16 acc value
            if t <= 0 {
                32767
            } else {
                let q = isqrt((t as u128) << 40);
                sat16((((1u128 << 34) + q / 2) / q) as i64)
            }
        })
        .collect()
}

/// SILU table: input Q4.11, output sat16(rhe(x·σ(x) · 2^11)).
/// σ(x) = e^x/(1+e^x) computed from the same integer exp core.
pub fn gen_silu() -> Vec<i16> {
    (0..LUT_ENTRIES)
        .map(|i| {
            let t = (i as i32 - 32768) as i64; // x in Q11
            let v = exp_q32(t as i32) as i128; // e^x in Q32
            let sigma_q32 = ((v << 32) / ((1i128 << 32) + v)) as i64; // ∈ [0, 2^32]
            // x(Q11)·σ(Q32) = Q43 ≤ 2^15·2^32 = 2^47 — fits i64; >>32 → Q11.
            sat16(rnd(t.wrapping_mul(sigma_q32), 32))
        })
        .collect()
}

pub fn to_bytes(table: &[i16]) -> Vec<u8> {
    table.iter().flat_map(|v| v.to_le_bytes()).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exp_anchor_values() {
        let t = gen_exp();
        assert_eq!(t[32768], 16384, "e^0 = 1.0 in Q1.14 exactly");
        assert_eq!(t[0], 0, "e^-16 underflows Q14");
        assert_eq!(t[LUT_ENTRIES - 1], 32767, "e^+16 saturates");
        // e^(-ln2) = 0.5: t = -ln2·2048 ≈ -1420 → ≈ 8192 (±2 ulp).
        let half = t[32768 - 1420] as i64;
        assert!((half - 8192).abs() <= 2, "e^-0.6934 ≈ 0.5, got {half}");
        // Monotone nondecreasing over the whole domain.
        assert!(t.windows(2).all(|w| w[0] <= w[1]));
    }

    #[test]
    fn rsqrt_anchor_values() {
        let t = gen_rsqrt();
        let at = |m: i32| t[(m + 32768) as usize];
        assert_eq!(at(0), 32767, "m=0 sentinel");
        assert_eq!(at(-5), 32767, "negative inputs hit the sentinel");
        assert_eq!(at(1), 16384, "1/√1 = 1.0 in Q2.14");
        assert_eq!(at(4), 8192, "1/√4 = 0.5");
        assert_eq!(at(16384), 128, "1/√(128²) = 1/128");
        // Monotone nonincreasing on the positive domain.
        assert!((1..32767).all(|m| at(m) >= at(m + 1)));
    }

    #[test]
    fn silu_anchor_values() {
        let t = gen_silu();
        let at = |x: i32| t[(x + 32768) as usize] as i64;
        assert_eq!(at(0), 0, "silu(0) = 0");
        // silu(1.0) = 0.7311 → Q11 ≈ 1497 (±3).
        assert!((at(2048) - 1497).abs() <= 3, "silu(1) got {}", at(2048));
        // Large positive: silu(x) → x.
        assert!((at(30000) - 30000).abs() <= 4);
        // Large negative: → 0 from below; global minimum ≈ −0.2785 → ≈ −570.
        assert_eq!(at(-32768), 0);
        let min = (-32768..32767).map(at).min().unwrap();
        assert!((-580..=-560).contains(&min), "silu minimum ≈ -0.2785, got {min}");
    }
}
