/// Verifies dispute::reclaim against a REAL Reclaim-format attestor
/// signature (eth-account EIP-191 secp256k1 over the canonical claim;
/// generated by tools/reclaim — see reclaim_vector.json). Proves a zkTLS
/// web proof of a real news URL verifies on-chain via Sui-native ecrecover.
#[test_only]
module dispute::reclaim_tests;

use dispute::reclaim;

// claim: a Reclaim http proof that bbc.com/news served a headline.
const PROVIDER: vector<u8> = x"68747470";
const PARAMETERS: vector<u8> = x"7b2275726c223a2268747470733a2f2f7777772e6262632e636f6d2f6e657773222c226d6574686f64223a22474554222c22726573706f6e73654d617463686573223a5b7b2274797065223a22636f6e7461696e73222c2276616c7565223a2253746172736869702072656163686573206f72626974227d5d7d";
const CONTEXT: vector<u8> = x"7b22657874726163746564506172616d6574657273223a7b22686561646c696e65223a2253746172736869702072656163686573206f72626974227d2c2270726f766964657248617368223a223078626263227d";
const OWNER: vector<u8> = x"307831376335313835313637343031656430306366356635623266633937643962626664623764303235";
const SIG: vector<u8> = x"1885e46afbaca803bc46409eb951f9ecce0651ad8fcadc66a08d43af657455a969ff320c6e07af007bc8b2788d407df009381ae4dcf6513ff5f9d067888783551b";
const ATTESTOR: vector<u8> = x"17c5185167401ed00cf5f5b2fc97d9bbfdb7d025";

#[test]
fun real_attestor_signature_verifies_onchain() {
    let p = reclaim::verify(PROVIDER, PARAMETERS, CONTEXT, OWNER, 1734200000, 1, SIG, ATTESTOR);
    assert!(reclaim::attestor(&p) == ATTESTOR, 0);
    assert!(reclaim::timestamp_s(&p) == 1734200000, 1);
}

#[test]
#[expected_failure(abort_code = 1, location = dispute::reclaim)]
fun wrong_attestor_rejected() {
    let bad = x"00112233445566778899aabbccddeeff00112233";
    let _ = reclaim::verify(PROVIDER, PARAMETERS, CONTEXT, OWNER, 1734200000, 1, SIG, bad);
}

#[test]
#[expected_failure(abort_code = 1, location = dispute::reclaim)]
fun tampered_claim_rejected() {
    // flip one byte of context -> identifier changes -> recovered signer != attestor
    let mut ctx = CONTEXT;
    *(&mut ctx[10]) = ctx[10] ^ 1;
    let _ = reclaim::verify(PROVIDER, PARAMETERS, ctx, OWNER, 1734200000, 1, SIG, ATTESTOR);
}
